### ISSUE TITLE
About datasets and EDA

### ISSUE THREAD

**Issue by 17011813** [waico/SKAB#32]
Good Morning :)

I wanna know when are you gonna upload the English version of EDA on kaggle?
Also, where can I get upcoming update to v1.0? I want to get more anomaly and anomaly-free dataset :)
Can u plz share more valve datasets?

Thanks for your great work!
Have a great day.

**Comment by YKatser** [comment]
Hello @17011813 !

Some answers to your comments and questions:
- The English version of EDA on Kaggle will be prepared in February 2022.
- The upcoming update will be available in the repository. Currently, we are repairing the testbed because it has been broken for some time. We hope to finish the repair soon and finish collecting data to release v1.0.
- We will focus a lot on the anomaly-free dataset, so, please, stay tuned)
- We will add more valve datasets, as well as other datasets.

We will be glad to answer more questions if you have any!

Kind regards,
Iurii
